### ISSUE TITLE
在最后一步./createChannelAndInstallChaincode.sh的时候出错

### ISSUE THREAD

**Issue by vogali** [cdljsj/bill-endorse#1]
POST request Join channel on Org2

{"success":true,"message":"Successfully joined peers in organization org2 to the channel 'mychannel'"}

POST Install chaincode on Org1

Successfully Installed chaincode on organization org1

POST instantiate chaincode on peer1 of Org1

Failed to order the transaction. Error code: undefined

Total execution time : 8 secs ...

**Comment by vogali** [comment]
似乎是这里的问题
```
echo "POST instantiate chaincode on peer1 of Org1"
echo
curl -s -X POST \
  http://localhost:4000/channels/mychannel/chaincodes \
  -H "authorization: Bearer $ORG1_TOKEN" \
  -H "content-type: application/json" \
  -d '{
	"chaincodeName":"mycc",
	"chaincodeVersion":"v0",
	"args":["a","100","b","200"]
}'
echo
echo
```

**Comment by gavinwang2010** [comment]
Same issue with you. Have you solve it?

**Comment by gavinwang2010** [comment]
update to fabric 1.2

**Comment by vogali** [comment]
yes, update to 1.2
